# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  charlesphotography.co.uk:
    site_hosts:
      - canonical: charlesphotography.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@charlesphotography.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
  charlesdigital.co.uk:
    site_hosts:
      - canonical: charlesdigital.test
    local_path: ../site2 # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@charlesdigital.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
  charleslanguageservices.com:
    site_hosts:
      - canonical: charleslanguageservices.test
    local_path: ../charleslanguageservices # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@charleslanguageservices.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
