# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  charlesphotography.co.uk:
    site_hosts:
      - canonical: charlesphotography.co.uk
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:elvinos/charlesphotography.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  charlesdigital.co.uk:
    site_hosts:
      - canonical: charlesdigital.co.uk
    local_path: ../site2 # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:elvinos/charlesphotography.git # replace with your Git repo URL
    repo_subtree_path: site2 # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
