# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  charlesphotography.co.uk:
    site_hosts:
      - canonical: charlesphotography.co.uk
    local_path: ../charlesphotography # path targeting local Bedrock site directory (relative to Ansible root)
    theme: charlesphoto # targeting site main theme for build-before
    repo: git@github.com:elvinos/charlesphotography.git # replace with your Git repo URL
    repo_subtree_path: charlesphoto # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  charlesdigital.co.uk:
    site_hosts:
      - canonical: charlesdigital.co.uk
    local_path: ../charlesdigital # path targeting local Bedrock site directory (relative to Ansible root)
    theme: sage
    repo: git@github.com:elvinos/charlesphotography.git # replace with your Git repo URL
    repo_subtree_path: charlesdigital # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
  charleslanguageservices.com:
    site_hosts:
      - canonical: charleslanguageservices.com
    local_path: ../charleslanguageservices # path targeting local Bedrock site directory (relative to Ansible root)
    theme: sage
    repo: git@github.com:elvinos/charlesphotography.git # replace with your Git repo URL
    repo_subtree_path: charleslanguageservices # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
